apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workload
  namespace: workload
  labels:
    release: kube-prom-stack
    app: workload
spec:
  namespaceSelector:
    matchNames:
      - workload
  selector:
    matchLabels:
      app: workload
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 5s
